services:
  web:
    image: tarefacoin-backend
    container_name: tarefacoin-backend
    networks:
      - mysql-network
      - tarefacoin-net
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"

networks:
  tarefacoin-net:
    external: true
  mysql-network:
    external: true